---
## Собираем образ из ~/ansible/roles/start_consul/files/Dockerfile ##
- name: build image consul_img:v1.20.1
  docker_image:
    build:
      path: /home/lex/DEVOPS/WORKS/ansible/roles/start_consul/files 
    name: consul_img
    tag: v1.20.1
    source: build
    state: present

## deploy контейнер  ##
- name: deploy docker container consul1.test.rnds
  docker_container:
    name: consul1.test.rnds
    image: consul_img:v1.20.1
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://127.66.16.7"]
    #   interval: 15s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    state: started
    auto_remove: true
    network_mode: host 
    command: ["consul", "agent",
      "-ui",
      "-server",
      "-node", "agent01",
      "-auto-reload-config",
      "-config-dir", "/etc/consul.d/",
      "-data-dir", "/consul/data",
      # "-advertise", "192.168.88.126",
      "-advertise", "{{  ansible_enp7s0.ipv4.address }}",
      "-bootstrap-expect", "1",
      "-bind", "0.0.0.0",
      # "-client", "192.168.88.126",
      "-client", "{{  ansible_enp7s0.ipv4.address }}",
      "-server-port", "8300",
      "-dns-port", "8053",
      "-http-port", "8500",
      "-serf-lan-port", "8301",
      "-serf-wan-port", "8302",
      "-log-level", "info"
    ]
    