

services:
  ng-proxy:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/docker_info:/usr/share/nginx/html 
   #   - ./nginx/proxy.conf:/etc/nginx/proxy.conf
   #   - ./nginx/ssl/:/etc/nginx/ssl/
    network_mode: host
    ports:
      - 443:443
      - 80:80