x-log: &log
  options:
    max-size: '50m'
    max-file: '3'
    labels: com.docker.compose.service
  driver: json-file

x-base: &base
  restart: always
  stop_grace_period: ${STOP_GRACE_PERIOD-30}s
  logging: *log

services:
  tp-roxy:
    container_name: traefik-gate
    image: traefik:latest
    <<: *base
    volumes:
      - ./configs:/etc/traefik/configs:ro
      - ./configs/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./ssl/:/etc/traefik/ssl/
    ports:
      - 443:443
      - 80:80
