---

# - import_role:
#     name: nomad_service


- name: copy nomad config
  template:
    src: /home/lex/ansible/roles/start_nomad/templates/nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    #dest: /home/lex/ansible/roles/start_nomad/files/nomad.hcl

- name: start nomad
  service:
    name: nomad
    state: restarted
    enabled: yes

# - name: start nomad
#   shell: nomad agent -config /home/lex/ansible/roles/start_nomad/files/nomad.hcl > /dev/null &




