---

- name: copy nomad config
  template:
    src: /home/lex/DEVOPS/WORKS/ansible/roles/start_nomad/templates/nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl

- name: start nomad
  service:
    name: nomad
    state: restarted
    enabled: yes

- name: wait up nomad
  wait_for: 
    port: 4646
    state: started


